- name: install config center
  hosts: configcenter
  sudo: True
  tasks:
    - name: install docker
      shell: sudo yum -y install docker-io
    - name: start docker
      shell: systemctl start docker
    - name: delete image
      shell: rm -f /root/configcenter.tar
    - name: copy image
      copy: src=/root/configcenter.tar dest=/root/configcenter.tar owner=root group=root mode=777
    - name: start docker service
      shell: systemctl start docker
    - name: stop container
      shell: docker stop ConfigCenter
      ignore_errors: yes
    - name: remove container
      shell: docker rm ConfigCenter
      ignore_errors: yes
    - name: remove image
      shell: docker rmi dockerloud/configcenter
      ignore_errors: yes
    - name: load image
      shell: docker load < /root/configcenter.tar
    - name: build and start container
      shell: docker run  --name ConfigCenter --net=host dockerloud/configcenter &
    - name: sleep 5s
      shell: sleep 5s
      ignore_errors: yes
    - name: start container
      shell: docker start ConfigCenter
      ignore_errors: yes