- name: install registration center
  hosts: registrationcenter
  sudo: True
  tasks:
    - name: install docker
      shell: sudo yum -y install docker-io
    - name: copy image
      copy: src=/tmp/registrationcenter.tar dest=/tmp/registrationcenter.tar owner=root group=root mode=777
    - name: start docker service
      shell: systemctl start docker
    - name: stop container
      shell: docker stop RegistrationCenter
      ignore_errors: yes
    - name: remove container
      shell: docker rm RegistrationCenter
      ignore_errors: yes
    - name: remove image
      shell: docker rmi dockerloud/registrationcenter
      ignore_errors: yes
    - name: load image
      shell: docker load < /tmp/registrationcenter.tar
    - name: build and start container
      shell: docker run  --name RegistrationCenter -p 1111:1111 dockerloud/registrationcenter &
    - name: sleep 5s
      shell: sleep 5s
      ignore_errors: yes
    - name: sleep 5s
      shell: docker start RegistrationCenter
      ignore_errors: yes
      
